/// File dialog commands using Tauri v2 dialog plugin
///
/// This module provides native file open/save dialogs that integrate
/// with the system's file browser (Finder on macOS, Explorer on Windows, etc.).

use std::path::PathBuf;
use std::sync::mpsc;

/// Open file dialog for selecting a file to open
///
/// # Arguments
/// * `app` - Tauri AppHandle for dialog access
///
/// # Returns
/// * `Ok(Some(path))` - User selected a file (absolute path)
/// * `Ok(None)` - User cancelled the dialog
/// * `Err(String)` - Dialog failed (rare)
///
/// # Dialog Behavior
/// - Starts in user's home directory
/// - Filters to `.md` and `.txt` files
/// - Single file selection (not multi-select)
#[tauri::command]
pub async fn open_file_dialog(app: tauri::AppHandle) -> Result<Option<String>, String> {
    use tauri_plugin_dialog::DialogExt;

    let (tx, rx) = mpsc::channel();

    app.dialog()
        .file()
        .add_filter("Markdown", &["md"])
        .add_filter("Text", &["txt"])
        .add_filter("All Files", &["*"])
        .pick_file(move |path| {
            let path_string = path.map(|p| p.to_string());
            let _ = tx.send(path_string);
        });

    // Wait for the result
    rx.recv().map_err(|e| {
        eprintln!("open_file_dialog error: {}", e);
        format!("File dialog failed: {}", e)
    })
}

/// Save file dialog for selecting a file path to save
///
/// # Arguments
/// * `app` - Tauri AppHandle for dialog access
///
/// # Returns
/// * `Ok(Some(path))` - User selected save location (absolute path)
/// * `Ok(None)` - User cancelled the dialog
/// * `Err(String)` - Dialog failed (rare)
///
/// # Dialog Behavior
/// - Starts in user's home directory
/// - Default filename: `untitled.md`
/// - Filters to `.md` and `.txt` files
/// - Allows creating new file or overwriting existing
#[tauri::command]
pub async fn save_file_dialog(
    app: tauri::AppHandle,
    suggested_filename: Option<String>,
) -> Result<Option<String>, String> {
    use tauri_plugin_dialog::DialogExt;

    let (tx, rx) = mpsc::channel();
    let filename = suggested_filename.unwrap_or_else(|| "untitled.md".to_string());

    app.dialog()
        .file()
        .add_filter("Markdown", &["md"])
        .add_filter("Text", &["txt"])
        .add_filter("All Files", &["*"])
        .set_file_name(&filename)
        .save_file(move |path| {
            let path_string = path.map(|p| p.to_string());
            let _ = tx.send(path_string);
        });

    // Wait for the result
    rx.recv().map_err(|e| {
        eprintln!("save_file_dialog error: {}", e);
        format!("File dialog failed: {}", e)
    })
}

/// Save file dialog for exporting as HTML.
///
/// # Arguments
/// * `app` - Tauri AppHandle for dialog access
/// * `suggested_filename` - Pre-populated filename in the dialog (e.g. "notes.html")
///
/// # Returns
/// * `Ok(Some(path))` - User selected save location (absolute path as string)
/// * `Ok(None)` - User cancelled the dialog
/// * `Err(String)` - Dialog failed (rare)
///
/// # Dialog Behavior
/// - Starts in user's home directory
/// - Default filename: value of `suggested_filename`
/// - Primary filter: HTML Files (.html, .htm)
/// - Secondary filter: All Files (*)
#[tauri::command]
pub async fn save_html_dialog(
    app: tauri::AppHandle,
    suggested_filename: String,
) -> Result<Option<String>, String> {
    use tauri_plugin_dialog::DialogExt;

    let (tx, rx) = mpsc::channel();

    app.dialog()
        .file()
        .add_filter("HTML Files", &["html", "htm"])
        .add_filter("All Files", &["*"])
        .set_file_name(&suggested_filename)
        .save_file(move |path| {
            let path_string = path.map(|p| p.to_string());
            let _ = tx.send(path_string);
        });

    rx.recv().map_err(|e| {
        eprintln!("save_html_dialog error: {}", e);
        format!("File dialog failed: {}", e)
    })
}

/// Save file dialog for exporting a clipboard-pasted image as PNG.
///
/// Structurally identical to `save_html_dialog` — same mpsc channel pattern,
/// same return type — substituting a PNG file filter for the HTML filter.
///
/// # Arguments
/// * `app` - Tauri AppHandle for dialog access
/// * `suggested_filename` - Pre-populated filename in the dialog
///   (e.g. "20260505-143022.png", generated by `generateImageFilename` in JS)
///
/// # Returns
/// * `Ok(Some(path))` - User confirmed a save location (absolute path as string)
/// * `Ok(None)` - User cancelled the dialog
/// * `Err(String)` - Dialog infrastructure failed (rare)
///
/// # Dialog Behaviour
/// - Primary filter: "PNG Image" (.png)
/// - Secondary filter: "All Files" (*)
/// - Pre-populated filename: value of `suggested_filename`
///
/// # No Rust tests
/// Dialog commands require a running AppHandle and are excluded from
/// `cargo test` by project convention (same as `save_html_dialog`).
#[tauri::command]
pub async fn save_image_dialog(
    app: tauri::AppHandle,
    suggested_filename: String,
) -> Result<Option<String>, String> {
    use tauri_plugin_dialog::DialogExt;

    let (tx, rx) = mpsc::channel();

    app.dialog()
        .file()
        .add_filter("PNG Image", &["png"])
        .add_filter("All Files", &["*"])
        .set_file_name(&suggested_filename)
        .save_file(move |path| {
            // Convert the dialog result (FilePath | None) to a plain String option.
            let path_string = path.map(|p| p.to_string());
            let _ = tx.send(path_string);
        });

    rx.recv().map_err(|e| {
        eprintln!("save_image_dialog error: {}", e);
        format!("File dialog failed: {}", e)
    })
}

/// Open file picker dialog filtered to common image and vector formats.
/// Used by the layout config wizard when the user selects a cover image or icon.
#[tauri::command]
pub async fn open_asset_dialog(app: tauri::AppHandle) -> Result<Option<String>, String> {
    use tauri_plugin_dialog::DialogExt;

    let (tx, rx) = mpsc::channel();

    app.dialog()
        .file()
        .add_filter("Images & SVG", &["jpg", "jpeg", "png", "gif", "webp", "avif", "svg"])
        .add_filter("All Files", &["*"])
        .pick_file(move |path| {
            let path_string = path.map(|p| p.to_string());
            let _ = tx.send(path_string);
        });

    rx.recv().map_err(|e| {
        eprintln!("open_asset_dialog error: {}", e);
        format!("File dialog failed: {}", e)
    })
}

/// Open folder picker dialog for selecting a directory.
///
/// # Arguments
/// * `app` - Tauri AppHandle for dialog access
/// * `default_path` - Optional starting directory for the picker (e.g. working directory)
///
/// # Returns
/// * `Ok(Some(path))` - User selected a folder (absolute path)
/// * `Ok(None)` - User cancelled the dialog
/// * `Err(String)` - Dialog failed (rare)
#[tauri::command]
pub async fn open_folder_dialog(
    app: tauri::AppHandle,
    default_path: Option<String>,
) -> Result<Option<String>, String> {
    use tauri_plugin_dialog::DialogExt;

    let (tx, rx) = mpsc::channel();

    let mut builder = app.dialog().file();
    if let Some(path) = default_path {
        builder = builder.set_directory(PathBuf::from(path));
    }
    builder.pick_folder(move |path| {
        let path_string = path.map(|p| p.to_string());
        let _ = tx.send(path_string);
    });

    rx.recv().map_err(|e| {
        eprintln!("open_folder_dialog error: {}", e);
        format!("Folder dialog failed: {}", e)
    })
}
