// AUTO-GENERATED by scripts/fetch-material-icons.mjs — do not edit by hand
// Material Symbols Outlined (weight 400) — https://fonts.google.com/icons
// License: Apache 2.0  https://github.com/marella/material-symbols

/** Material Symbols: inventory_2 */
export const ICON_VAULT =
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960"><path d="M180-80q-24.75 0-42.37-17.63Q120-115.25 120-140v-483q-17-6-28.5-21.39T80-680v-140q0-24.75 17.63-42.38Q115.25-880 140-880h680q24.75 0 42.38 17.62Q880-844.75 880-820v140q0 20.22-11.5 35.61T840-623v483q0 24.75-17.62 42.37Q804.75-80 780-80H180Zm0-540v480h600v-480H180Zm-40-60h680v-140H140v140Zm220 260h240v-60H360v60Zm120 40Z"/></svg>`;

/** Material Symbols: folder */
export const ICON_FOLDER =
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960"><path d="M140-160q-24 0-42-18.5T80-220v-520q0-23 18-41.5t42-18.5h281l60 60h339q23 0 41.5 18.5T880-680v460q0 23-18.5 41.5T820-160H140Zm0-60h680v-460H456l-60-60H140v520Zm0 0v-520 520Z"/></svg>`;

/** Material Symbols: folder_open */
export const ICON_FOLDER_OPEN =
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960"><path d="M140-160q-23 0-41.5-18.5T80-220v-520q0-23 18.5-41.5T140-800h281l60 60h339q23 0 41.5 18.5T880-680H455l-60-60H140v520l102-400h698L833-206q-6 24-22 35t-41 11H140Zm63-60h572l84-340H287l-84 340Zm0 0 84-340-84 340Zm-63-460v-60 60Z"/></svg>`;

/** Material Symbols: folder_managed */
export const ICON_FOLDER_MANAGED =
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960"><path d="m691-82-5-48q-23-7-42-18.5T611-173l-42 20-35-54 38-30q-5-19-5-41.5t5-41.5l-38-30 35-55 42 20q14-12 33-23.5t42-18.5l5-49h60l6 49q23 7 42 18.5t33 23.5l42-20 35 55-38 30q5 19 5 41.5t-5 41.5l38 30-35 54-42-20q-14 13-33 24.5T757-130l-6 48h-60Zm103-124q29-29 29-73t-29-73q-29-29-73-29t-73 29q-29 29-29 73t29 73q29 29 73 29t73-29Zm-654-14v-520 220-20 320Zm0 60q-24 0-42-18.5T80-220v-520q0-23 18-41.5t42-18.5h281l60 60h339q23 0 41.5 18.5T880-680v194q-14-11-28.5-19T820-520v-160H456l-60-60H140v520h328q4 16 9 31t13 29H140Z"/></svg>`;

/** Material Symbols: description */
export const ICON_FILE =
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960"><path d="M319-250h322v-60H319v60Zm0-170h322v-60H319v60ZM220-80q-24 0-42-18t-18-42v-680q0-24 18-42t42-18h361l219 219v521q0 24-18 42t-42 18H220Zm331-554v-186H220v680h520v-494H551ZM220-820v186-186 680-680Z"/></svg>`;

/** Material Symbols: article */
export const ICON_FILE_MD =
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960"><path d="M277-279h275v-60H277v60Zm0-171h406v-60H277v60Zm0-171h406v-60H277v60Zm-97 501q-24 0-42-18t-18-42v-600q0-24 18-42t42-18h600q24 0 42 18t18 42v600q0 24-18 42t-42 18H180Zm0-60h600v-600H180v600Zm0-600v600-600Z"/></svg>`;

/** Material Symbols: image */
export const ICON_FILE_IMAGE =
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960"><path d="M180-120q-24 0-42-18t-18-42v-600q0-24 18-42t42-18h600q24 0 42 18t18 42v600q0 24-18 42t-42 18H180Zm0-60h600v-600H180v600Zm56-97h489L578-473 446-302l-93-127-117 152Zm-56 97v-600 600Z"/></svg>`;

/** Material Symbols: data_object */
export const ICON_FILE_JSON =
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960"><path d="M570-160v-60h120q21 0 35.5-14.38Q740-248.75 740-270v-100q0-37 22.5-66t57.5-40v-8q-35-10-57.5-39.5T740-590v-100q0-21.25-14.37-35.63Q711.25-740 690-740H570v-60h120q46 0 78 32.08 32 32.09 32 77.92v100q0 21.25 14.38 35.62Q828.75-540 850-540h30v120h-30q-21.25 0-35.62 14.37Q800-391.25 800-370v100q0 45.83-32.08 77.92Q735.83-160 690-160H570Zm-300 0q-46 0-78-32.08-32-32.09-32-77.92v-100q0-21.25-14.37-35.63Q131.25-420 110-420H80v-120h30q21.25 0 35.63-14.38Q160-568.75 160-590v-100q0-45.83 32.08-77.92Q224.17-800 270-800h120v60H270q-21 0-35.5 14.37Q220-711.25 220-690v100q0 37-22.5 66.5T140-484v8q35 11 57.5 40t22.5 66v100q0 21.25 14.38 35.62Q248.75-220 270-220h120v60H270Z"/></svg>`;

/** Material Symbols: code */
export const ICON_FILE_CODE =
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960"><path d="M320-242 80-482l242-242 43 43-199 199 197 197-43 43Zm318 2-43-43 199-199-197-197 43-43 240 240-242 242Z"/></svg>`;

/** Material Symbols: chevron_right */
export const ICON_CHEVRON =
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960"><path d="M530-481 332-679l43-43 241 241-241 241-43-43 198-198Z"/></svg>`;

/** Material Symbols: keyboard_arrow_down */
export const ICON_EXPAND =
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960"><path d="M480-344 240-584l43-43 197 197 197-197 43 43-240 240Z"/></svg>`;

/** Material Symbols: chip_extraction */
export const ICON_UNMOUNT =
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960"><path d="M480-121q-75 0-140.5-28.5t-114-77q-48.5-48.5-77-114T120-481q0-75 28.5-140.5t77-114q48.5-48.5 114-77T480-841v60q-124 0-212 88t-88 212q0 125.36 88 212.68Q356-181 480-181v60Zm173-173-42-43 113-113H360v-60h364L611-624l42-42 186 186-186 186Z"/></svg>`;

/** Material Symbols: preview */
export const ICON_PREVIEW =
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960"><path d="M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H200Zm0-80h560v-480H200v480Zm133.5-124.5Q269-369 240-440q29-71 93.5-115.5T480-600q82 0 146.5 44.5T720-440q-29 71-93.5 115.5T480-280q-82 0-146.5-44.5Zm248.5-42q46-26.5 72-73.5-26-47-72-73.5T480-540q-56 0-102 26.5T306-440q26 47 72 73.5T480-340q56 0 102-26.5ZM480-440Zm42.5 42.5Q540-415 540-440t-17.5-42.5Q505-500 480-500t-42.5 17.5Q420-465 420-440t17.5 42.5Q455-380 480-380t42.5-17.5Z"/></svg>`;
